# Generated by Django 2.2.16 on 2020-09-30 09:57

import django.core.validators
from django.db import migrations, models
import secure_documents.models
import storages.backends.sftpstorage
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateGeneralDocuments',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('passport_scan', models.FileField(blank=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to=secure_documents.models.candidates_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg'])])),
                ('international_passport_scan', models.FileField(blank=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to=secure_documents.models.candidates_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg'])])),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('registration_number_document', models.FileField(blank=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to=secure_documents.models.candidates_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg'])])),
                ('is_sepa_region', models.BooleanField(default=True)),
                ('iban_code', models.CharField(blank=True, max_length=50)),
                ('bank_account_document', models.FileField(blank=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to=secure_documents.models.candidates_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg'])])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateSecureDocument',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('document_type', models.IntegerField(choices=[(1, 'Job Offer'), (2, 'Contract'), (3, 'Invoice')])),
                ('secure_document', models.FileField(storage=storages.backends.sftpstorage.SFTPStorage(), upload_to=secure_documents.models.candidates_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyGeneralDocuments',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('tax_number', models.CharField(blank=True, max_length=50)),
                ('tax_number_document', models.FileField(blank=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to=secure_documents.models.companies_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg'])])),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('registration_number_document', models.FileField(blank=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to=secure_documents.models.companies_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg'])])),
                ('is_sepa_region', models.BooleanField(default=True)),
                ('iban_code', models.CharField(blank=True, max_length=50)),
                ('bank_account_document', models.FileField(blank=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to=secure_documents.models.companies_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg'])])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanySecureDocument',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('document_type', models.IntegerField(choices=[(1, 'Job Offer'), (2, 'Contract'), (3, 'Invoice')])),
                ('secure_document', models.FileField(storage=storages.backends.sftpstorage.SFTPStorage(), upload_to=secure_documents.models.companies_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
