# Generated by Django 2.2.13 on 2020-06-04 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0017_auto_20200603_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Project name')),
                ('project_description', models.TextField(blank=True, verbose_name='Project description')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.CompanyProfile', verbose_name='Company')),
            ],
        ),
    ]
