# Generated by Django 2.2.13 on 2020-06-05 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200603_1734'),
        ('projects', '0003_auto_20200605_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounts.CompanyProfile', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
