# Generated by Django 2.2.13 on 2020-06-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_position_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='prosition',
        ),
        migrations.AddField(
            model_name='position',
            name='salary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='projects.Salary'),
        ),
        migrations.AlterField(
            model_name='position',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='projects.Project', verbose_name='Project'),
        ),
    ]
