# Generated by Django 2.2.13 on 2020-06-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200605_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='additional_description',
            field=models.TextField(blank=True, verbose_name='Additional description'),
        ),
    ]
