# Generated by Django 2.2.13 on 2020-06-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200618_1806'),
        ('projects', '0009_auto_20200618_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_applications', to='accounts.CandidateProfile')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_applications', to='projects.Position')),
            ],
            options={
                'unique_together': {('candidate', 'position')},
            },
        ),
    ]
