# Generated by Django 2.2.13 on 2020-06-25 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_positionapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='offers',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(255, message='Please enter minimum 255 symbols')], verbose_name='What we offer'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(255, message='Please enter minimum 255 symbols')], verbose_name='Position title'),
        ),
        migrations.AlterField(
            model_name='position',
            name='requirements',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(255, message='Please enter minimum 255 symbols')], verbose_name='Requirements'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(255, message='Please enter minimum 255 symbols')], verbose_name='Project description'),
        ),
    ]
