# Generated by Django 2.2.13 on 2020-06-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200625_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_title',
            field=models.CharField(max_length=255, verbose_name='Position title'),
        ),
    ]
