# Generated by Django 2.2.14 on 2020-07-23 13:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20200721_1223'),
        ('projects', '0012_auto_20200625_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='project_documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_documents', to='accounts.CompanyProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PositiontDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='position_documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_documents', to='accounts.CompanyProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
