# Generated by Django 2.2.14 on 2020-07-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20200721_1223'),
        ('projects', '0013_positiontdocument_projectdocument'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PositiontDocument',
            new_name='PositionDocument',
        ),
    ]
