# Generated by Django 2.2.15 on 2020-08-12 11:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20200723_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='communication_languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('en', 'English'), ('de', 'German')], max_length=5, verbose_name='Communication languages'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('CHF', 'Swiss Franc')], max_length=3),
        ),
    ]
