# Generated by Django 2.2.15 on 2020-08-21 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20200812_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='offers',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(255, message='Please enter minimum 255 symbols')], verbose_name='What we offer'),
        ),
        migrations.AlterField(
            model_name='position',
            name='requirements',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(255, message='Please enter minimum 255 symbols')], verbose_name='Requirements'),
        ),
    ]
