# Generated by Django 2.2.15 on 2020-08-24 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20200812_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='offers_de',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(255, message='Please enter minimum 255 symbols')], verbose_name='What we offer'),
        ),
        migrations.AddField(
            model_name='position',
            name='offers_en',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(255, message='Please enter minimum 255 symbols')], verbose_name='What we offer'),
        ),
        migrations.AddField(
            model_name='position',
            name='position_title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Position title'),
        ),
        migrations.AddField(
            model_name='position',
            name='position_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Position title'),
        ),
        migrations.AddField(
            model_name='position',
            name='requirements_de',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(255, message='Please enter minimum 255 symbols')], verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='position',
            name='requirements_en',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(255, message='Please enter minimum 255 symbols')], verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_description_de',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(255, message='Please enter minimum 255 symbols')], verbose_name='Project description'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_description_en',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(255, message='Please enter minimum 255 symbols')], verbose_name='Project description'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Project name'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Project name'),
        ),
    ]
