# Generated by Django 2.2.15 on 2020-08-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20200824_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='additional_description',
        ),
    ]
