# Generated by Django 2.2.15 on 2020-08-25 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20200821_0758'),
        ('projects', '0017_remove_project_additional_description'),
    ]

    operations = [
    ]
