# Generated by Django 2.2.16 on 2020-10-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20200930_2003'),
        ('projects', '0018_merge_20200825_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='specialization',
            field=models.ManyToManyField(related_name='positions', to='accounts.Specialization'),
        ),
    ]
