# Generated by Django 2.2.16 on 2020-10-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_position_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='experience',
            field=models.IntegerField(choices=[(1, '< 1 year'), (2, '1-3 years'), (3, '3-5 years'), (4, '5+ years')], verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='position',
            name='specialization',
            field=models.ManyToManyField(blank=True, related_name='positions', to='accounts.Specialization'),
        ),
    ]
