# Generated by Django 2.2.16 on 2020-10-08 10:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0020_auto_20201002_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='communication_languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('en', 'English'), ('de', 'German')],
                                                              db_index=True, max_length=5,
                                                              verbose_name='Communication languages'),
        ),
        migrations.AlterField(
            model_name='position',
            name='experience',
            field=models.IntegerField(choices=[(1, '< 1 year'), (2, '1-3 years'), (3, '3-5 years'), (4, '5+ years')],
                                      db_index=True, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='position',
            name='experience_level',
            field=models.IntegerField(choices=[(1, 'Junior'), (2, 'Middle'), (3, 'Senior'), (4, 'Lead')], db_index=True,
                                      verbose_name='Experience level'),
        ),
        migrations.AlterField(
            model_name='position',
            name='job_type',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[(1, 'Full time'), (2, 'Part time'), (3, 'Contract'), (4, 'Internship')], db_index=True,
                max_length=7, verbose_name='Job type'),
        ),
        migrations.AlterField(
            model_name='position',
            name='specialization',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='positions',
                                         to='accounts.Specialization'),
        ),
        migrations.AlterField(
            model_name='position',
            name='technologies',
            field=models.ManyToManyField(db_index=True, related_name='position_technologies', to='accounts.Technology'),
        ),
    ]
