# Generated by Django 2.2.16 on 2020-10-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_position_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='country',
            field=models.CharField(blank=True, choices=[('ch', 'Switzerland'), ('de', 'Germany'), ('at', 'Austria'), ('be', 'Belgium'), ('ca', 'Canada'), ('dk', 'Denmark'), ('fi', 'Finland'), ('fr', 'France'), ('is', 'Iceland'), ('it', 'Italy'), ('li', 'Liechtenstein'), ('lu', 'Luxembourg'), ('nl', 'Netherlands'), ('no', 'Norway'), ('se', 'Sweden'), ('gb', 'United Kingdom'), ('us', 'United States')], db_index=True, max_length=255, null=True, verbose_name='Country'),
        ),
    ]
