# Generated by Django 2.2.16 on 2020-10-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20201015_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='specialization',
            field=models.ManyToManyField(db_index=True, related_name='positions', to='accounts.Specialization'),
        ),
    ]
