# Generated by Django 2.2.16 on 2020-11-06 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20201022_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(255, message='Please enter minimum 255 symbols')], verbose_name='Project description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description_de',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(255, message='Please enter minimum 255 symbols')], verbose_name='Project description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description_en',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(255, message='Please enter minimum 255 symbols')], verbose_name='Project description'),
        ),
    ]
