# Generated by Django 2.2.16 on 2020-11-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20201110_1025'),
        ('projects', '0026_auto_20201106_1129'),
    ]

    operations = [
    ]
