# Generated by Django 2.2.17 on 2020-12-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_merge_20201110_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='country',
            field=models.CharField(choices=[('ch', 'Switzerland'), ('de', 'Germany'), ('at', 'Austria'), ('be', 'Belgium'), ('ca', 'Canada'), ('dk', 'Denmark'), ('fi', 'Finland'), ('fr', 'France'), ('is', 'Iceland'), ('it', 'Italy'), ('li', 'Liechtenstein'), ('lu', 'Luxembourg'), ('nl', 'Netherlands'), ('no', 'Norway'), ('se', 'Sweden'), ('gb', 'United Kingdom'), ('us', 'United States')], db_index=True, default='ch', max_length=255, verbose_name='Country'),
            preserve_default=False,
        ),
    ]
