# Generated by Django 2.2.12 on 2020-05-21 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200521_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='candidate_images', verbose_name='Profile image'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
