# Generated by Django 2.2.12 on 2020-06-02 10:25

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200602_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
