# Generated by Django 2.2.12 on 2020-06-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_technology_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='additional_information',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Information'),
        ),
    ]
