# Generated by Django 2.2.12 on 2020-06-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200603_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='cover_letter',
            field=models.TextField(blank=True, null=True, verbose_name='Cover letter'),
        ),
    ]
