# Generated by Django 2.2.12 on 2020-06-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200603_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='experience_level',
            field=models.IntegerField(choices=[(1, 'Junior'), (2, 'Middle'), (3, 'Senior'), (4, 'Lead')], default=1, verbose_name='Experience level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='job_type',
            field=models.IntegerField(choices=[(1, 'Full time'), (2, 'Part time'), (3, 'Contract'), (4, 'Internship')], default=1, verbose_name='Job type'),
            preserve_default=False,
        ),
    ]
