# Generated by Django 2.2.12 on 2020-06-03 14:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200603_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='job_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Full time'), (2, 'Part time'), (3, 'Contract'), (4, 'Internship')], max_length=7, verbose_name='Job type'),
        ),
    ]
