# Generated by Django 2.2.13 on 2020-06-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200622_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatelink',
            name='url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Link url'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone_number',
            field=models.CharField(max_length=16, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='phone_number',
            field=models.CharField(max_length=16, verbose_name='Phone number'),
        ),
    ]
