# Generated by Django 2.2.13 on 2020-06-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200625_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='first_name',
            field=models.CharField(error_messages={'max_length': 'Please enter maximum 255 symbols'}, max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='last_name',
            field=models.CharField(error_messages={'max_length': 'Please enter maximum 255 symbols'}, max_length=255, verbose_name='Last name'),
        ),
    ]
