# Generated by Django 2.2.13 on 2020-06-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20200625_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatelink',
            name='url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link url'),
        ),
    ]
