# Generated by Django 2.2.14 on 2020-07-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200625_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='technology_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Technology name'),
        ),
    ]
