# Generated by Django 2.2.14 on 2020-07-21 04:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_companydocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydocument',
            name='document',
            field=models.FileField(upload_to='company_documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])]),
        ),
        migrations.CreateModel(
            name='CandidateHiring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_companies', to='accounts.CandidateProfile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hired_candidates', to='accounts.CompanyProfile')),
            ],
            options={
                'unique_together': {('company', 'candidate')},
            },
        ),
    ]
