# Generated by Django 2.2.14 on 2020-07-21 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_candidateprofile_is_identified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_description',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(255, message='Please enter minimum 255 symbols')], verbose_name='Description'),
        ),
    ]
