# Generated by Django 2.2.14 on 2020-07-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20200721_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_size',
            field=models.IntegerField(blank=True, choices=[(1, '<50'), (2, '50-200'), (3, '200-500'), (4, '500+')], null=True, verbose_name='Company Size'),
        ),
    ]
