# Generated by Django 2.2.15 on 2020-08-12 11:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20200806_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='communication_languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('en', 'English'), ('de', 'German')], max_length=5, verbose_name='Communication Language'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='communication_languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('en', 'English'), ('de', 'German')], max_length=5, verbose_name='Communication languages'),
        ),
        migrations.AlterField(
            model_name='hourlyrate',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('CHF', 'Swiss Franc')], max_length=3),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link url'),
        ),
    ]
