# Generated by Django 2.2.15 on 2020-08-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20200812_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_website',
            field=models.CharField(blank=True, max_length=255, verbose_name='Website'),
        ),
    ]
