# Generated by Django 2.2.15 on 2020-08-24 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20200813_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='adress_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Adress'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='adress_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Adress'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='city_de',
            field=models.CharField(max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='city_en',
            field=models.CharField(max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='country_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='country_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='cover_letter_de',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(255, message='Please enter between 255 and 1000 symbols'), django.core.validators.MaxLengthValidator(1000, message='Please enter between 255 and 1000 symbols')], verbose_name='Cover letter'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='cover_letter_en',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(255, message='Please enter between 255 and 1000 symbols'), django.core.validators.MaxLengthValidator(1000, message='Please enter between 255 and 1000 symbols')], verbose_name='Cover letter'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='job_position_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Job position'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='job_position_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Job position'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='nationality_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='nationality_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='city_de',
            field=models.CharField(max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='city_en',
            field=models.CharField(max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_adress_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Adress'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_adress_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Adress'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_description_de',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(255, message='Please enter minimum 255 symbols')], verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_description_en',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(255, message='Please enter minimum 255 symbols')], verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Company name'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Company name'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='country_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='country_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='industry_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='industry_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Industry'),
        ),
    ]
