# Generated by Django 2.2.16 on 2020-09-22 08:19

import accounts.models
import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20200824_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='color',
            field=colorfield.fields.ColorField(default=accounts.models.generate_random_color, max_length=18),
        ),
    ]
