# Generated by Django 2.2.16 on 2020-10-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20201008_2219'),
        ('accounts', '0045_auto_20201012_1144'),
    ]

    operations = [
    ]
