# Generated by Django 2.2.16 on 2020-10-15 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20201015_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyprofile',
            name='country_de',
        ),
        migrations.RemoveField(
            model_name='agencyprofile',
            name='country_en',
        ),
    ]
