# Generated by Django 2.2.16 on 2020-10-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_agencyhiring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='specialization',
            field=models.ManyToManyField(related_name='technologies', to='accounts.Specialization'),
        ),
    ]
