# Generated by Django 2.2.16 on 2020-10-27 08:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20201022_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyCandidateCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cv_file', models.FileField(upload_to='agency_candidate_cvs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_candidate_cvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
