# Generated by Django 2.2.16 on 2020-10-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20201022_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='sms_phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
