# Generated by Django 2.2.16 on 2020-10-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20201023_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='sms_phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sms_phone_number',
            new_name='phone_number',
        ),
    ]
