# Generated by Django 2.2.16 on 2020-10-27 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_auto_20201023_1627'),
        ('accounts', '0052_agencycandidatecv'),
    ]

    operations = [
    ]
