# Generated by Django 2.2.17 on 2020-11-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_merge_20201027_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='has_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_password',
            field=models.BooleanField(default=True),
        ),
    ]
