# Generated by Django 2.2.17 on 2020-11-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_auto_20201123_1053'),
        ('accounts', '0055_auto_20201118_1257'),
    ]

    operations = [
    ]
