# Generated by Django 2.2.17 on 2020-11-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_employeeprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Position at company'),
        ),
    ]
