# Generated by Django 2.2.17 on 2020-11-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_auto_20201125_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencyprofile',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('view_agencyprofile', 'Can view agency profile'),), 'verbose_name': 'agency profile', 'verbose_name_plural': 'agency profiles'},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'permissions': (('view_agencyprofile', 'Can view agency profile'),), 'verbose_name': 'comany profile', 'verbose_name_plural': 'company profiles'},
        ),
    ]
