# Generated by Django 2.2.17 on 2020-11-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_auto_20201126_1408'),
        ('accounts', '0060_auto_20201125_1452'),
    ]

    operations = [
    ]
