# Generated by Django 2.2.17 on 2020-11-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_auto_20201130_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencyprofile',
            options={'verbose_name': 'agency profile', 'verbose_name_plural': 'agency profiles'},
        ),
    ]
