# Generated by Django 2.2.17 on 2020-12-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_merge_20201126_1741'),
        ('accounts', '0062_auto_20201130_1600'),
    ]

    operations = [
    ]
