# Generated by Django 2.2.14 on 2020-07-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('question_headline', models.CharField(max_length=255, verbose_name='Question headline')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('question_type', models.CharField(choices=[('COMPANY', 'For company'), ('CANDIDATE', 'For candidate')], max_length=32, verbose_name='Question type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
