# Generated by Django 2.2.15 on 2020-08-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_de',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_headline_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Question headline'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_headline_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Question headline'),
        ),
    ]
