# Generated by Django 2.2.17 on 2020-12-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20200820_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('COMPANY', 'For company'), ('CANDIDATE', 'For candidate'), ('AGENCY', 'For agencies')], max_length=32, verbose_name='Question type'),
        ),
    ]
